spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      path: /console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
